### ISSUE TITLE
[リクエスト] モバイル表示用オプション

### ISSUE THREAD

**Issue by Foxy-null** [shigeyukey/Anki-Discord-Sidebar#1]
アドオンの設定に、モバイル用サイトとして表示するか否かを選択できる機能を追加していただけると幸いです。

PC表示では、絵文字でリアクションする際に横幅が足りず、絵文字リストが画面外にはみ出すなどの不具合が生じてしまいます。モバイル表示に切り替えることでこの問題を回避できます。

**Comment by shigeyukey** [comment]
本来はPC版ではなくモバイル版でのみ表示する予定でしたが､モバイル版で表示するとDiscordのページが真っ白になるバグがあります｡
これはDiscord側の問題なので､アドオンでは解決方法が今のところありません(ChromeとかSafariとかのブラウザでも真っ白になるバグが発生します)
将来的にDiscord側の問題が解決されたら導入できると思います｡(結構前からあるバグのようなのであまり期待できませんが...)

**Comment by Foxy-null** [comment]
ご返信ありがとうございます。
Close as not plannedしておきますね。
